onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@sbc-connect/nuxt-auth"
  - "@sbc-connect/nuxt-base"
  - "@sbc-connect/nuxt-forms"
  - "@sbc-connect/nuxt-pay"
  - "@tailwindcss/oxide"
  - esbuild
  - vue-demi
