name: EXPRESS-CHECKOUT GCP CD

on:
  push:
    branches:
      - main
    paths:
      - "web/express-checkout/**"
      - ".github/workflows/express-checkout-cd.yml"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
        - dev
        - test
        - sandbox
        - prod

jobs:
  express-checkout-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-cd.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "express-checkout"
      working_directory: "./web/express-checkout"
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
